# Generated by Django 4.1.7 on 2023-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10, verbose_name='學號')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('dep', models.CharField(max_length=30, verbose_name='系所')),
                ('grade', models.CharField(max_length=30, verbose_name='年級')),
            ],
        ),
    ]
