# Generated by Django 4.1.7 on 2023-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='年級'),
        ),
    ]
