# Generated by Django 4.1.7 on 2023-10-03 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='密碼'),
            preserve_default=False,
        ),
    ]
