# Generated by Django 4.1.7 on 2023-10-14 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_d1051831_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='課程時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d1051831_course',
            name='time',
            field=models.CharField(default=123, max_length=10, verbose_name='課程時間'),
            preserve_default=False,
        ),
    ]
