# Generated by Django 4.1.7 on 2023-10-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_time_d1051831_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=25, verbose_name='課程時間'),
        ),
        migrations.AlterField(
            model_name='d1051831_course',
            name='time',
            field=models.CharField(max_length=25, verbose_name='課程時間'),
        ),
    ]
