# Generated by Django 4.1.7 on 2023-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_time_alter_d1051831_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='節次'),
        ),
        migrations.AddField(
            model_name='d1051831_course',
            name='session',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='節次'),
        ),
    ]
