# Generated by Django 4.1.7 on 2023-10-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_course_session_remove_d1051831_course_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='week',
            field=models.CharField(max_length=3, null=True, verbose_name='星期'),
        ),
        migrations.AddField(
            model_name='d1051831_course',
            name='week',
            field=models.CharField(max_length=3, null=True, verbose_name='星期'),
        ),
    ]
