# Generated by Django 4.1.7 on 2023-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_end_session_alter_course_start_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, verbose_name='選課代碼'),
        ),
        migrations.AlterField(
            model_name='d1051831_course',
            name='code',
            field=models.CharField(max_length=10, verbose_name='選課代碼'),
        ),
    ]
