# Generated by Django 4.1.7 on 2023-10-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_student_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='student_number',
            field=models.CharField(default='123', max_length=15, verbose_name='學號'),
        ),
    ]
