# Generated by Django 4.1.7 on 2023-11-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_course_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(default='123', max_length=15, verbose_name='學號'),
        ),
    ]
