# Generated by Django 4.1.7 on 2023-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classs',
            field=models.CharField(default='', max_length=20, verbose_name='開課班級'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='選課代碼'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default='', verbose_name='學分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_session',
            field=models.IntegerField(verbose_name='結束節次'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='科目名稱'),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_elective',
            field=models.CharField(default='', max_length=20, verbose_name='必選修'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_session',
            field=models.IntegerField(verbose_name='開始節次'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=25, verbose_name='課程時間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='week',
            field=models.CharField(default='', max_length=3, verbose_name='星期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=15, verbose_name='系級'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=10, verbose_name='學生名稱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=15, verbose_name='學號'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='classs',
            field=models.CharField(default='', max_length=20, verbose_name='開課班級'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='選課代碼'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='credit',
            field=models.DecimalField(decimal_places=0, default='', max_digits=10, verbose_name='學分'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='end_session',
            field=models.IntegerField(verbose_name='結束節次'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='科目名稱'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='required_elective',
            field=models.CharField(default='', max_length=20, verbose_name='必選修'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='start_session',
            field=models.IntegerField(verbose_name='開始節次'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='student_number',
            field=models.CharField(default='', max_length=15, verbose_name='學號'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='time',
            field=models.CharField(default='', max_length=25, verbose_name='課程時間'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='week',
            field=models.CharField(default='', max_length=3, verbose_name='星期'),
        ),
    ]
