# Generated by Django 4.1.7 on 2023-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_course_classs_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='學分'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_session',
            field=models.IntegerField(default=0, verbose_name='結束節次'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_session',
            field=models.IntegerField(default=0, verbose_name='開始節次'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='學分'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='end_session',
            field=models.IntegerField(default=0, verbose_name='結束節次'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='start_session',
            field=models.IntegerField(default=0, verbose_name='開始節次'),
        ),
    ]
