# Generated by Django 4.1.7 on 2023-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_course_credit_alter_course_end_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='end_session',
            field=models.IntegerField(default=12, verbose_name='結束節次'),
        ),
    ]
