# Generated by Django 4.1.7 on 2023-11-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_alter_student_course_end_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='end_session',
            field=models.IntegerField(default=0, verbose_name='結束節次'),
        ),
    ]
